import Foundation

/// Weather values taken directly from Open-Meteo. Numbers are rendered
/// straight from this snapshot — the model only writes `practicalNote`.
struct WeatherSnapshot: Codable, Hashable {
    var locationName: String
    var latitude: Double
    var longitude: Double
    var temperature: Double
    var apparentTemperature: Double
    var high: Double
    var low: Double
    var precipitationProbability: Int
    var conditionCode: Int
    var windSpeed: Double
    var sunrise: Date?
    var sunset: Date?
    /// "°C" or "°F"
    var unitSymbol: String
    /// One literal, practical line generated by the editor model,
    /// e.g. "Rain likely after 3 PM."
    var practicalNote: String?

    var conditionDescription: String {
        WeatherSnapshot.describe(code: conditionCode)
    }

    var symbolName: String {
        WeatherSnapshot.sfSymbol(code: conditionCode)
    }

    /// WMO weather interpretation codes used by Open-Meteo.
    static func describe(code: Int) -> String {
        switch code {
        case 0: return "Clear"
        case 1: return "Mostly clear"
        case 2: return "Partly cloudy"
        case 3: return "Overcast"
        case 45, 48: return "Fog"
        case 51, 53, 55: return "Drizzle"
        case 56, 57: return "Freezing drizzle"
        case 61, 63, 65: return "Rain"
        case 66, 67: return "Freezing rain"
        case 71, 73, 75: return "Snow"
        case 77: return "Snow grains"
        case 80, 81, 82: return "Rain showers"
        case 85, 86: return "Snow showers"
        case 95: return "Thunderstorm"
        case 96, 99: return "Thunderstorm with hail"
        default: return "—"
        }
    }

    static func sfSymbol(code: Int) -> String {
        switch code {
        case 0: return "sun.max"
        case 1: return "sun.min"
        case 2: return "cloud.sun"
        case 3: return "cloud"
        case 45, 48: return "cloud.fog"
        case 51, 53, 55, 56, 57: return "cloud.drizzle"
        case 61, 63, 65, 66, 67: return "cloud.rain"
        case 71, 73, 75, 77, 85, 86: return "cloud.snow"
        case 80, 81, 82: return "cloud.heavyrain"
        case 95, 96, 99: return "cloud.bolt.rain"
        default: return "cloud"
        }
    }

    func formatted(_ value: Double) -> String {
        "\(Int(value.rounded()))\(unitSymbol)"
    }
}
